apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:MasayaAoyama/argocd-hpa-test.git
    targetRevision: master
    path: manifests/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
